#define MSG_HEADER_SIZE 4
#define MSG_SIZE 100
#define MSG_MAX_SIZE (MSG_HEADER_SIZE + MSG_SIZE)
#define MSG_MAX_AMOUNT 10
#define MSG_TIMEOUT 5

#define ID_SENDER 0
#define ID_RECEIVER 1

#define PDU_HEADER_SIZE 8
#define TIMEOUT_2 800000L
#define TIMEOUT_1 800000000L

#define OPC_MENU 0
#define OPC_SEND_FILE 1
#define OPC_RECEIVE_FILE 2

#define SOCKET_TIMEOUT 5